indexer:
  chains:
    tron:
      name: "tron"
      nodes:
        - "https://tron-rpc.publicnode.com"
        - "https://api.trongrid.io"
        - "https://tron.drpc.org"
      start_block: 74399849
      batch_size: 10
      poll_interval: "3s" # the TRON network produces a block around every 3s
      rate_limit:
        requests_per_second: 10 # Maximum 10 requests per second per node
        burst_size: 20 # Allow burst of up to 20 requests
      client:
        request_timeout: "10s" # Timeout for individual requests
        max_retries: 3 # Maximum retry attempts
        retry_delay: "5s" # Delay between retries
    evm:
      name: "evm"
      nodes:
        - "https://ethereum-rpc.publicnode.com"
        - "https://1rpc.io/eth"
        - "https://eth-mainnet.g.alchemy.com/v2/demo"
      start_block: 22988209
      batch_size: 10
      poll_interval: "5s"
      rate_limit:
        requests_per_second: 5
        burst_size: 10
      client:
        request_timeout: "30s"
        max_retries: 3
        retry_delay: "10s"

  nats:
    url: "nats://localhost:4222"
    subject_prefix: "blockchain.indexer"

  storage:
    type: "memory"
